### ISSUE TITLE
Inference/Prediction notebooks available?

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [lihaoliu-cambridge/simultaneous_semantic_and_instance_segmentation#1]
Hello team, thanks for this repo! I was wondering if I could get hold of any Inference/Prediction notebooks, which I can use to predict your model on my H&E dataset.

Thanks, Ajinkya

**Comment by lihaoliu-cambridge** [comment]
Hi Ajinkya,

Thank you for reaching out with your question, and for your interest in our project.

At the moment we don't have a specific notebook prepared for the inference. Instead, I recommend that you run the testing code directly via the command line. Here are some instructions to guide you through the process:

1. **For the Instance Segmentation Part:**
   - Please refer to the instructions provided in the Detectron2 documentation for testing. 

2. **For the Semantic Segmentation Part:**
   - Please follow the instructions detailed in the Hover-Net documentation for testing.

Once you have obtained results from both instance and semantic segmentation, we do provide the customer NMS code to merge the results cohesively. Please refer to our documentation, specifically under the section “Usage - 5,” for more details on this process.

I hope this information is helpful for you. If you encounter any issues or have further questions, please don't hesitate to reach back out. 

Best regards,
Lihao.
